### ISSUE TITLE
input custom mhm human objects and clothes.

### ISSUE THREAD

**Issue by perseus784** [makehuman-js/makehuman-js-example#3]
Hi,
How to import custom human objects mhm file and and also how to add more clothes than what is already there. I can see json files are present inside the data folder, how to convert these mhm files to json files and also how to convert how to convert standard clothes files which is generated by python to the json cloth structure?

**Comment by wassname** [comment]
I used this repo to convert them: https://github.com/makehuman-js/makehuman-data

It's not very documented since only a handful of people have used it. A few people have asked previously but the issues are a bit scattered over the 3 makehuman repos. Here are the relevant ones:

- pose https://github.com/makehuman-js/makehuman-js/issues/9
- proxies/clothes https://github.com/makehuman-js/makehuman-js/issues/8
- proxies/clothes https://github.com/makehuman-js/makehuman-data/issues/1
- target https://github.com/makehuman-js/makehuman-data/issues/2
