### ISSUE TITLE
Alternative to XHRLoader

### ISSUE THREAD

**Issue by oscarrr112** [makehuman-js/makehuman-js-example#5]
Hello,
I am not familiar with js, but I need to use the repo to finish my project. In your example, you use XHRLoader to load the config, but it seems that it is no longer provided by the three.js. As a consequence, I wonder if there any alternative to the XHRLoader to do the same job.
Oscarr112.

**Comment by wassname** [comment]
You'll need to learn some js to use this project I'm afraid since it's mostly js.

You should use the correct version of three.js, the one in package.json. For some background on npm package management [see this article for siilar ones](https://nodesource.com/blog/the-basics-of-package-json-in-node-js-and-npm/).. In the new versions [XHRLoader](https://threejs.org/docs/#api/en/deprecated/DeprecatedList) has been renamed, along with lots of other things, meaning it's easier to use the correct version.

**Comment by oscarrr112** [comment]
that’s the problem, i just don’t know the new name of the XHRLoader😂😂😂

**Comment by oscarrr112** [comment]
i have learnt js for some time, but i am not that familiar with library provided by others. so, that’s the problem, i just don’t know the new name of the XHRLoader😂😂😂

**Comment by wassname** [comment]
That's good. 

But it sounds like you are using an unsupported version of three.js so the loader is just one of the many things you will need to fix in order to be compatible with the version your using (which is?).

As for the new name, If you check the links I posted above, one of the links is to Three.js's deprecated list, which will give you the new name (just cntrl+f and search in the page for XHRLoader).
